baseURL = "https://kalimar.github.io/complete-computer-guitar-guide/#"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-learn"

[params]
themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]